### ISSUE TITLE
Political Violence among Party Affiliation

### ISSUE THREAD

**Issue by BBarr-PDAP** [Police-Data-Accessibility-Project/data-projects#11]
Someone has requested help on a data project: 

**Submission Notes**
------------------------------------------------------------------------------------------------------------------------------------------------------

I am looking for data on political violence from the left versus the right including legal accuracy from leadership FBI and MediaBin relation to individual instances. 

**Location**
------------------------------------------------------------------------------------------------------------------------------------------------------

Looking for growing threats of political violence in the United States, the intensity of violence, and whether political influence is truly influential in causing violence

**Requirements**
---------------------------------------------------------------------------------------------------------------------------------------------------

Data, from 20007 to the present, on politically motivated acts of violence

**How to Help**
---------------------------------------------------------------------------------------------------------------------------------------------------

Leave a comment if you'd like to help. Do you have ideas, questions, or need any more information to get started?

**Comment by josh-chamberlain** [comment]
Need more info from the requestor, who was unresponsive.
