### ISSUE TITLE
Allegheny County availability of translation services in police stops

### ISSUE THREAD

**Issue by BBarr-PDAP** [Police-Data-Accessibility-Project/data-projects#19]
Someone has requested help on a data project: 

**Submission notes**
------------------------------------------------------------------------------------------------------------------------------------------------------

Are there data on the actual availability of translation services in police stops?  

**Location**
---------------------------------------------------------------------------------------------------------------------------------------------------

Allegheny County, PA

**Requirements**
---------------------------------------------------------------------------------------------------------------------------------------------------

Data location and analysis

**How to help**
------------------------------------------------------------------------------------------------------------------------------------------------------

Leave a comment if you'd like to help. Do you have ideas, questions, or need any more information to get started?

**Comment by josh-chamberlain** [comment]
There doesn't seem to be a source of information about how available translation services are.
