### ISSUE TITLE
Oakland, CA Calls for Services

### ISSUE THREAD

**Issue by BBarr-PDAP** [Police-Data-Accessibility-Project/data-projects#20]
Someone has requested help on a data project: 

**Submission notes**
------------------------------------------------------------------------------------------------------------------------------------------------------

Looking for Calls for Services in Oakland, CA for a longer time range than 48 hours. 

**Location**
---------------------------------------------------------------------------------------------------------------------------------------------------

Oakland Police Department - CA 

**Requirements**
---------------------------------------------------------------------------------------------------------------------------------------------------

Calls for Services

**How to help**
------------------------------------------------------------------------------------------------------------------------------------------------------

Leave a comment if you'd like to help. Do you have ideas, questions, or need any more information to get started?

**Comment by josh-chamberlain** [comment]
http://gisapps1.mapoakland.com/callsforservice/ 

We wrote a web scraper to preserve more data: https://github.com/Police-Data-Accessibility-Project/github-actions-demo/
