### ISSUE TITLE
Washington, D.C. Calls for Services

### ISSUE THREAD

**Issue by BBarr-PDAP** [Police-Data-Accessibility-Project/data-projects#21]
Someone has requested help on a data project: 

**Submission notes**
------------------------------------------------------------------------------------------------------------------------------------------------------

Looking for Calls for Services in Washington, D.C. 

**Location**
---------------------------------------------------------------------------------------------------------------------------------------------------

Washington Metropolitan Police Department - DC

**Requirements**
---------------------------------------------------------------------------------------------------------------------------------------------------

Calls for Services

**How to help**
------------------------------------------------------------------------------------------------------------------------------------------------------

Leave a comment if you'd like to help. Do you have ideas, questions, or need any more information to get started?

**Comment by josh-chamberlain** [comment]
Data source here: https://data-sources.pdap.io/data-sources/rec2zpgmx8yFgRTlN

This is an aggregated source without much information, but we could request additional records.
