### ISSUE TITLE
Denver, CO Calls for Service

### ISSUE THREAD

**Issue by BBarr-PDAP** [Police-Data-Accessibility-Project/data-projects#22]
Someone has requested help on a data project: 

**Submission notes**
------------------------------------------------------------------------------------------------------------------------------------------------------

Looking for Calls for Services in Denver, Colorado. 

**Location**
---------------------------------------------------------------------------------------------------------------------------------------------------

Denver Police Department - CO 

**Requirements**
---------------------------------------------------------------------------------------------------------------------------------------------------

Calls for Services

**How to help**
------------------------------------------------------------------------------------------------------------------------------------------------------

Leave a comment if you'd like to help. Do you have ideas, questions, or need any more information to get started?

**Comment by josh-chamberlain** [comment]
Requestor withdrew the issue. No records were found online, and they did not want to pursue a records request.
