### ISSUE TITLE
New York City, NY Calls for Services

### ISSUE THREAD

**Issue by BBarr-PDAP** [Police-Data-Accessibility-Project/data-projects#23]
Someone has requested help on a data project: 

**Submission notes**
------------------------------------------------------------------------------------------------------------------------------------------------------

Looking for Calls for Services in NYC, NY. 

**Location**
---------------------------------------------------------------------------------------------------------------------------------------------------

New York City Police Department - NY 

**Requirements**
---------------------------------------------------------------------------------------------------------------------------------------------------

Calls for Services

**How to help**
------------------------------------------------------------------------------------------------------------------------------------------------------

Leave a comment if you'd like to help. Do you have ideas, questions, or need any more information to get started?

**Comment by josh-chamberlain** [comment]
https://data-sources.pdap.io/data-sources/recUidt9bOm0SIRcE
