### ISSUE TITLE
Sacramento, CA Calls for Services 

### ISSUE THREAD

**Issue by BBarr-PDAP** [Police-Data-Accessibility-Project/data-projects#24]
Someone has requested help on a data project: 

**Submission notes**
------------------------------------------------------------------------------------------------------------------------------------------------------

Looking for Calls for Services in Sacramento, CA. 

**Location**
---------------------------------------------------------------------------------------------------------------------------------------------------

Sacramento Police Department - CA 

**Requirements**
---------------------------------------------------------------------------------------------------------------------------------------------------

Calls for Services

**How to help**
------------------------------------------------------------------------------------------------------------------------------------------------------

Leave a comment if you'd like to help. Do you have ideas, questions, or need any more information to get started?

**Comment by josh-chamberlain** [comment]
Data source here: https://data-sources.pdap.io/data-sources/rec42MAFfkx9hwiWi

This source appears to have been removed. 311 calls are available.
