### ISSUE TITLE
Lodi, CA Crime reports and police activity

### ISSUE THREAD

**Issue by BBarr-PDAP** [Police-Data-Accessibility-Project/data-projects#28]
Someone has requested help on a data project: 

**Submission notes**
------------------------------------------------------------------------------------------------------------------------------------------------------

Objective is to understand crime reports and police activity in Lodi, California. 

**Location**
---------------------------------------------------------------------------------------------------------------------------------------------------

Lodi Police Department - CA 

**Requirements**
---------------------------------------------------------------------------------------------------------------------------------------------------

Incident reports

**How to help**
------------------------------------------------------------------------------------------------------------------------------------------------------

Leave a comment if you'd like to help. Do you have ideas, questions, or need any more information to get started?

**Comment by josh-chamberlain** [comment]
Lodi sources: https://data-sources.pdap.io/search/all/lodi
