### ISSUE TITLE
Detroit MI arrests, complaints, calls for services 

### ISSUE THREAD

**Issue by BBarr-PDAP** [Police-Data-Accessibility-Project/data-projects#29]
Someone has requested help on a data project: 

**Submission notes**
------------------------------------------------------------------------------------------------------------------------------------------------------

Looking to collate information on arrests, complaints, and calls for service to determine which calls for service are being met most and least successfully by the Detroit Police Department. This will help with upcoming budget negotiation.

**Location**
---------------------------------------------------------------------------------------------------------------------------------------------------

Detroit Police Department - MI 

**Requirements**
---------------------------------------------------------------------------------------------------------------------------------------------------

Arrests, complaints, calls for services records

**How to help**
------------------------------------------------------------------------------------------------------------------------------------------------------

Leave a comment if you'd like to help. Do you have ideas, questions, or need any more information to get started?

**Comment by josh-chamberlain** [comment]
Related:  https://github.com/kushie0/explore_police_data

This request was completed by connecting a volunteer to the requestor via email.
