### ISSUE TITLE
Detroit MI Shotspotter System 

### ISSUE THREAD

**Issue by BBarr-PDAP** [Police-Data-Accessibility-Project/data-projects#30]
Someone has requested help on a data project: 

**Submission notes**
------------------------------------------------------------------------------------------------------------------------------------------------------

Looking for historic alerts from Detroit's ShotSpotter system and information about the placement of ShotSpotter detectors. Also, interested in alerts which were dismissed and information about the processes and procedures related to handling the alerts.

**Location**
---------------------------------------------------------------------------------------------------------------------------------------------------

Detroit Police Department - MI

**Requirements**
---------------------------------------------------------------------------------------------------------------------------------------------------

Shotspotter information

**How to help**
------------------------------------------------------------------------------------------------------------------------------------------------------

Leave a comment if you'd like to help. Do you have ideas, questions, or need any more information to get started?

**Comment by josh-chamberlain** [comment]
We made a request for historic alerts and policies: https://www.muckrock.com/foi/detroit-314/shotspotter-policies-140369/#files
