### ISSUE TITLE
United States police use of deadly force and their victims demographics

### ISSUE THREAD

**Issue by BBarr-PDAP** [Police-Data-Accessibility-Project/data-projects#31]
Someone has requested help on a data project: 

**Submission notes**
------------------------------------------------------------------------------------------------------------------------------------------------------

I am trying to compare and contrast the demographics of police officers who engage in the use of deadly force with the demographics of their victims.

**Location**
---------------------------------------------------------------------------------------------------------------------------------------------------

United States; as many police agencies as possible 

**Requirements**
---------------------------------------------------------------------------------------------------------------------------------------------------

Demographics of police officers who engage in use of deadly force and demographics of victims

**How to help**
------------------------------------------------------------------------------------------------------------------------------------------------------

Leave a comment if you'd like to help. Do you have ideas, questions, or need any more information to get started?

**Comment by josh-chamberlain** [comment]
Closing as too broad.

This kind of data is not published directly, and there's no nationwide source of information about it. We are documenting sources of use of force, but they rarely include demographic information, especially about police officers: https://data-sources.pdap.io/search/force/all
