### ISSUE TITLE
Kedrain Monta Swann court case 

### ISSUE THREAD

**Issue by BBarr-PDAP** [Police-Data-Accessibility-Project/data-projects#32]
Someone has requested help on a data project: 

**Submission notes**
------------------------------------------------------------------------------------------------------------------------------------------------------

Looking for information on Kedrain Monta Swann cases and lawsuits. 

**Location**
---------------------------------------------------------------------------------------------------------------------------------------------------

Orange County

**Requirements**
---------------------------------------------------------------------------------------------------------------------------------------------------

Court case

**How to help**
------------------------------------------------------------------------------------------------------------------------------------------------------

Leave a comment if you'd like to help. Do you have ideas, questions, or need any more information to get started?

**Comment by josh-chamberlain** [comment]
Found 3 unrelated cases searching for the alleged shooter https://portal-nc.tylertech.cloud/Portal/

Granted by finding the docket numbers via "inmate search", and calling the courthouse who confirmed the case could be accessed only in person.
