### ISSUE TITLE
Pittsburgh Bureau of Police Traffic Stops

### ISSUE THREAD

**Issue by BBarr-PDAP** [Police-Data-Accessibility-Project/data-projects#34]
Someone has requested help on a data project: 

**Submission notes**
------------------------------------------------------------------------------------------------------------------------------------------------------

Traffic stops for the Pittsburgh Bureau of Police before and after the policy change to begin traffic stops based on secondary infractions: https://www.wesa.fm/politics-government/2023-01-12/pittsburgh-police-resume-secondary-traffic-stops-despite-city-ordinance-against-them

**Location**
---------------------------------------------------------------------------------------------------------------------------------------------------

Pittsburgh Bureau of Police

**Requirements**
---------------------------------------------------------------------------------------------------------------------------------------------------

Traffic stop records

**How to help**
------------------------------------------------------------------------------------------------------------------------------------------------------

Leave a comment if you'd like to help. Do you have ideas, questions, or need any more information to get started?

**Comment by josh-chamberlain** [comment]
We successfully requested traffic stops: https://www.muckrock.com/foi/pittsburgh-130/traffic-stops-140596/

At least one article used the data: https://www.publicsource.org/pittsburgh-police-traffic-stop-disparity-accountability-race/
