### ISSUE TITLE
Las Vegas, NV Officer-involved shootings

### ISSUE THREAD

**Issue by BBarr-PDAP** [Police-Data-Accessibility-Project/data-projects#36]
Someone has requested help on a data project: 

**Submission notes**
------------------------------------------------------------------------------------------------------------------------------------------------------

Requestor needs help manually researching and investigating officer-involved shootings in the Las Vegas area and maintaining a community-run database.

**Location**
---------------------------------------------------------------------------------------------------------------------------------------------------

Las Vegas Police Department , North Las Vegas Police Department, and Henderson Police Department - NV

**Requirements**
---------------------------------------------------------------------------------------------------------------------------------------------------

Officer-involved shooting records

**How to help**
------------------------------------------------------------------------------------------------------------------------------------------------------

Leave a comment if you'd like to help. Do you have ideas, questions, or need any more information to get started?

**Comment by josh-chamberlain** [comment]
We connected the requestor with a volunteer via email.
