### ISSUE TITLE
Seattle WA Rape & homicide records

### ISSUE THREAD

**Issue by BBarr-PDAP** [Police-Data-Accessibility-Project/data-projects#37]
Someone has requested help on a data project: 

**Submission notes**
------------------------------------------------------------------------------------------------------------------------------------------------------

What kinds of records do we need to document clearance rates for rape and homicide?

**Location**
---------------------------------------------------------------------------------------------------------------------------------------------------

Seattle, Washington 

**Requirements**
---------------------------------------------------------------------------------------------------------------------------------------------------

Data selection

**How to help**
------------------------------------------------------------------------------------------------------------------------------------------------------

Leave a comment if you'd like to help. Do you have ideas, questions, or need any more information to get started?

**Comment by josh-chamberlain** [comment]
Our response:

"It depends how you define “clearance”—and your ability to follow a case through to prosecution. Some agencies may define their clearance rate as as arrest, but not update their numbers if the charge is dropped. 
You could request a document about “clearance rates” from the police, but they may not have such a document lying around. You would also need to know how it was generated, and ideally see the underlying data.

In general it’s crime reports → arrests/charges → court cases/prosecutions.

FBI's NIBRS database may be a good starting point. It's missing a lot of data, and it's normalized so you're missing some context, but you can compare crime to arrests in the same department across specified time periods."
