### ISSUE TITLE
Los Angeles, CA Autopsy Report

### ISSUE THREAD

**Issue by BBarr-PDAP** [Police-Data-Accessibility-Project/data-projects#38]
Someone has requested help on a data project: 

**Submission notes**
------------------------------------------------------------------------------------------------------------------------------------------------------

Incident report: https://lasd.org/wp-content/uploads/2023/02/Transparency_011123_SCV_DIS_-Mercurio_Christopher_Lee_summary_013023.pdf

Autopsy report ID: 2023-00483

https://mec.lacounty.gov/purchase-case-documents/?caseNumber=2023-00483

https://github.com/datadesk/los-angeles-police-killings-data/blob/master/los-angeles-prosecutor-decisions.csv

**Location**
---------------------------------------------------------------------------------------------------------------------------------------------------

Los Angeles Sheriffs Department - CA

**Requirements**
---------------------------------------------------------------------------------------------------------------------------------------------------

Autopsy report

**How to help**
------------------------------------------------------------------------------------------------------------------------------------------------------

Leave a comment if you'd like to help. Do you have ideas, questions, or need any more information to get started?

**Comment by josh-chamberlain** [comment]
The requestor was hoping to avoid the document fee; there's no easy way around it.
