### ISSUE TITLE
Allegheny County PA data completion

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-projects#4]
## Task

For each agency in Allegheny County ([list here](https://airtable.com/app473MWXVJVaD7Es/shr82MU9ged2teeIv)), we need a valid agency homepage and as many URLs as possible.

For reference, Allegheny County data sources in table form: https://airtable.com/app473MWXVJVaD7Es/shrUzF2TE8bxxX7fW

Submit data sources: https://airtable.com/app473MWXVJVaD7Es/shrJafakrcmTxHU2i

## Things to capture:

- agency homepage (updated or new if missing)
- and data sources found that are not in the db (make a submission)
- once done with an agency, fill in the date last checked on the spreadsheet
- in particular, keep an eye out for _published policies_

## Notes

[Searching for data sources](https://docs.pdap.io/activities/contribute/submit-data-sources)
[Definition of a data source](https://docs.pdap.io/activities/terms-and-definitions/what-is-a-data-source)
[Record types taxonomy](https://docs.pdap.io/activities/data-dictionaries/record-types-taxonomy)

**Comment by BBarr-PDAP** [comment]
Here. I am going to look through already completed agencies to compare them to what has been documented, and then I will look into the missing ones. I would appreciate feedback after one submission, and then I will be comfortable filling those in as I go. Thank you.

**Comment by BBarr-PDAP** [comment]
Thank you, Josh, for those documents, they will certainly be helpful to me. I have reviewed them, and I am sure that I will reference them a few more times until I get the hang of things. I just wanted to make you aware of my schedule/availability. Tentatively, I will be available for 4-5 hours on Mondays, Tuesdays, Wednesdays, and Fridays to work on these projects--if needed I would put in the extra hours on the weekend during my free time. Today, I have some other responsibilities after work, so I will submit a few requests once I am free later this evening.  So, come Friday, I will certainly be submitting a lot more requests for you to approve, and hopefully I will have this done before we meet again on Tuesday.

**Comment by BBarr-PDAP** [comment]
I have one question for clarification regarding the data submission form: For the "Data Source Name" and "Source URL," would just the agency name and URL suffice for the smaller agencies, like the West Homestead example? Or would that be covered in the "Agency Described" and "Source URL"? Then for the larger agencies with additional data, like arrests or incident reports, would I put "Incident reports" for the "Data Source Name" and the link for that in the "Source URL"?

**Comment by josh-chamberlain** [comment]
@BBarr-PDAP thanks! Please spend the time you plan to allot to the project and get as far as you can, but don't stress about closing out the issue.

For "data source name", a lot of the time it's just `type of record` for `agency name or place`. "arrest records for chattanooga, TN" or "annual reports for madison, OH police". You could also just say "2023 arrest records" and then fill out the agency. Right now, we don't have many rules about this, do do your best! You can always [see examples here](https://airtable.com/shrUAtA8qYasEaepI).

The source URL is _just_ a link, so I would say repeating information you can see in the URL is ok.

**Comment by josh-chamberlain** [comment]
@BBarr-PDAP thanks for working on this!

I've taken a look at your submissions, and they look great! I think your descriptions got better over time, and you found a lot of updated homepages. I approved all the data source submissions aside from homepages.

For the updated agency homepages—we have a different table for those. Would you be able to switch to using the google sheet and entering them that way? If you update the "date last checked" property, we can keep track of your work, too. It doesn't need to be too accurate, just a "have we checked for sources this year" kinda thing.

These are the ones you submitted, in case it's helpful.

Churchhill Police Department - PA		https://www.churchillborough.com/government/department-overview/police
Wilkins Police Department - PA		https://wilkinstownship.com/departments/police.php
Penn Hills Police Department - PA		https://www.pennhillspolice.com/
Crafton Borough Police Department - PA		https://www.craftonborough.com/emergency-services
Allegheny Port Authority Transit Police - PA		https://www.rideprt.org/inside-Pittsburgh-Regional-Transit/rider-info/safety-and-security/police/
Ben Avon Police Department - PA		https://www.ohiotwp.org/index.asp?Type=B_BASIC&SEC={8165ACB6-0B74-44A5-AA57-0C190DF1371E}
Harmar Township Police Department - PA		https://www.harmartownship-pa.gov/police-department
West View Police Department - PA		https://www.wvboro.com/police-department
Verona Borough Police Department - PA		https://veronaborough.org/police/
Upper Saint Clair Township Police Department - PA		https://www.twpusc.org/departments/police/index.php
Brackenridge Police Department - PA		https://www.brackenridgeboro.com/police-department
Sharpsburg Police Department - PA		https://sharpsburgborough.com/police/
Frazer Township Police Department - PA		https://www.facebook.com/frazertownshippolice/
Springdale Borough Police Department - PA		https://springdaleboroughpd.com/
East Deer Township Police Department - PA		https://eastdeertownship.org/police-department/
East McKeesport Police Department - PA		https://www.eastmckeesportboro.com/department/police
Collier Township Police Department - PA		https://colliertownship.net/departments/police-department/
Edgeworth Borough Police Department - PA		https://edgeworthborough.org/services/police/
O'Hara Township Police Department - PA		https://www.ohara.pa.us/police-department
Findlay Township Police Department - PA		https://www.findlay.pa.us/151/Police
Lincoln Borough Police Department - PA		https://www.facebook.com/p/The-Lincoln-Borough-Police-Department-100077451275216/
Avalon Borough Police Department - PA		https://www.boroughofavalon.org/departments/avalonpolice/
South Heights Police Department - PA		https://www.sheightsboro.com/departments
Port Vue Borough Police Department - PA		https://portvue.org/local-government/police-department/
Etna Borough Police Department - PA		http://etnaborough.org/index.php/services/public-safety
North Versailles Township Police Department - PA		https://nvtpa.com/police/
Reserve Township Police Department - PA		https://reservetwp.com/home-1-2/police-department/

**Comment by BBarr-PDAP** [comment]
"For the updated agency homepages—we have a different table for those. Would you be able to switch to using the google sheet and entering them that way? If you update the "date last checked" property, we can keep track of your work, too. It doesn't need to be too accurate, just a "have we checked for sources this year" kinda thing." 
-Unfortunately, the Google Doc you created was not shared to me, because I remember you adding the Date Checked section, and if I open the Doc it doesn't not have that option. I can create my own Google Doc and share that with you if/unless you can share the one you made. For both the dates and updated homepages. 

Thank you for the feedback; I am definitely getting the feel for the submissions.

**Comment by josh-chamberlain** [comment]
[here's that spreadsheet](https://docs.google.com/spreadsheets/d/1QK4GNO9x0uz0nByIUijXMda2fYG6SPD8MpC1dziPyQE/edit?gid=164825506#gid=164825506) for reference

**Comment by josh-chamberlain** [comment]
I uploaded all the updates and removed duplicate agencies from the DB!
