### ISSUE TITLE
Pittsburgh PA Surveillance Technology 

### ISSUE THREAD

**Issue by BBarr-PDAP** [Police-Data-Accessibility-Project/data-projects#41]
Someone has requested help on a data project: 

**Submission notes**
------------------------------------------------------------------------------------------------------------------------------------------------------

I am now starting to work on biased deployment of police technology in Pittsburgh. This includes shot spotters, use of traffic and private cameras, automatic license plate readers, facial recognition, and predictive policing. Do you know how I can find out what Pittsburgh police are using and any data on their use?

**Location**
---------------------------------------------------------------------------------------------------------------------------------------------------

Pittsburgh Police Department - PA

**Requirements**
---------------------------------------------------------------------------------------------------------------------------------------------------

Surveillance technology in use

**How to help**
------------------------------------------------------------------------------------------------------------------------------------------------------

Leave a comment if you'd like to help. Do you have ideas, questions, or need any more information to get started?

**Comment by josh-chamberlain** [comment]
connected with Atlas of Surveillance: https://atlasofsurveillance.org/search?utf8=%E2%9C%93&location=pittsburgh&commit=Search+the+Data
