### ISSUE TITLE
New Orleans LA Incident reports

### ISSUE THREAD

**Issue by BBarr-PDAP** [Police-Data-Accessibility-Project/data-projects#42]
Someone has requested help on a data project: 

**Submission notes**
------------------------------------------------------------------------------------------------------------------------------------------------------

I'm trying to do a data science report on incident reports in the New Orleans metro area, possibly focused on police violence. Also would like to compare reports between Orleans and Jefferson parish, LA. 

**Location**
---------------------------------------------------------------------------------------------------------------------------------------------------

Orleans Parish Sheriff's Office - LA, Jefferson Davis Parish Sheriff's Office - LA

**Requirements**
---------------------------------------------------------------------------------------------------------------------------------------------------

Incident reports

**How to help**
------------------------------------------------------------------------------------------------------------------------------------------------------

Leave a comment if you'd like to help. Do you have ideas, questions, or need any more information to get started?

**Comment by josh-chamberlain** [comment]
These records are not accessible online. We can make a FOIA request if needed. The requestor was unresponsive.
