### ISSUE TITLE
Pittsburgh PA No-knock warrants

### ISSUE THREAD

**Issue by BBarr-PDAP** [Police-Data-Accessibility-Project/data-projects#44]
Someone has requested help on a data project: 

**Submission notes**
------------------------------------------------------------------------------------------------------------------------------------------------------

We were thinking about putting together some basic stats on how often Pittsburgh police are using no knock warrants, especially in the wake of the passage of Breonna's law which was supposed to have ended the practice here.

I've spent a fair bit of time this morning poking around city and county websites, but I'm not really able to find anything on them.

**Location**
---------------------------------------------------------------------------------------------------------------------------------------------------

Pittsburgh Bureau of Police

**Requirements**
---------------------------------------------------------------------------------------------------------------------------------------------------

Data/records of no-knock warrants

**How to help**
------------------------------------------------------------------------------------------------------------------------------------------------------

Leave a comment if you'd like to help. Do you have ideas, questions, or need any more information to get started?

**Comment by josh-chamberlain** [comment]
We were not able to obtain warrants. You can read more here: https://github.com/Police-Data-Accessibility-Project/caasi-help-desk/tree/main/no-knock_warrants
