### ISSUE TITLE
Allegheny County Jail average sentence length 

### ISSUE THREAD

**Issue by BBarr-PDAP** [Police-Data-Accessibility-Project/data-projects#45]
Someone has requested help on a data project: 

**Submission notes**
------------------------------------------------------------------------------------------------------------------------------------------------------

Looking for data on the average length of stay at the Allegheny County Jail. 

**Location**
---------------------------------------------------------------------------------------------------------------------------------------------------

Allegheny County Jail

**Requirements**
---------------------------------------------------------------------------------------------------------------------------------------------------

Jail records

**How to help**
------------------------------------------------------------------------------------------------------------------------------------------------------

Leave a comment if you'd like to help. Do you have ideas, questions, or need any more information to get started?

**Comment by josh-chamberlain** [comment]
This dashboard contains the answers: https://analytics.alleghenycounty.us/2021/03/04/allegheny-county-jail-population-management-dashboards-2/
