### ISSUE TITLE
Allegheny County Jail provisional detention

### ISSUE THREAD

**Issue by BBarr-PDAP** [Police-Data-Accessibility-Project/data-projects#46]
Someone has requested help on a data project: 

**Submission notes**
------------------------------------------------------------------------------------------------------------------------------------------------------

What are the most common reasons why inmates are on pre-trial detention, probation holds, etc. 

**Location**
---------------------------------------------------------------------------------------------------------------------------------------------------

Allegheny County Jail

**Requirements**
---------------------------------------------------------------------------------------------------------------------------------------------------

Jail records

**How to help**
------------------------------------------------------------------------------------------------------------------------------------------------------

Leave a comment if you'd like to help. Do you have ideas, questions, or need any more information to get started?

**Comment by josh-chamberlain** [comment]
This dashboard contains the answers: https://data-sources.pdap.io/data-sources/recn5peRrGMNEksXI
