### ISSUE TITLE
Allegheny County Jail PA most common commissary expenditure 

### ISSUE THREAD

**Issue by BBarr-PDAP** [Police-Data-Accessibility-Project/data-projects#48]
Someone has requested help on a data project: 

**Submission notes**
------------------------------------------------------------------------------------------------------------------------------------------------------

Is there information on the things that are most commonly purchased in commissary? 

**Location**
---------------------------------------------------------------------------------------------------------------------------------------------------

Allegheny County Jail - PA

**Requirements**
---------------------------------------------------------------------------------------------------------------------------------------------------

Commissary records

**How to help**
------------------------------------------------------------------------------------------------------------------------------------------------------

Leave a comment if you'd like to help. Do you have ideas, questions, or need any more information to get started?

**Comment by josh-chamberlain** [comment]
[2021 survey](https://alleghenycontroller.com/wp-content/uploads/2022/09/Pitt-School-of-Social-Work-ACJ-Needs-Assessment-Fall-2021.pdf) 

"In an open-ended response, the following items were the most frequently listed as necessary items that respondents purchased at the commissary: soap, toothpaste, shampoo, deodorant, lotion, toothbrush, toilet paper, socks, food, shoes, boxers"
