### ISSUE TITLE
Allegheny County Jail PA Phone calls 

### ISSUE THREAD

**Issue by BBarr-PDAP** [Police-Data-Accessibility-Project/data-projects#49]
Someone has requested help on a data project: 

**Submission notes**
------------------------------------------------------------------------------------------------------------------------------------------------------

How much is the average phone call in Allegheny County Jail? 

**Location**
---------------------------------------------------------------------------------------------------------------------------------------------------

Allegheny County Jail - PA

**Requirements**
---------------------------------------------------------------------------------------------------------------------------------------------------

Cost policy

**How to help**
------------------------------------------------------------------------------------------------------------------------------------------------------

Leave a comment if you'd like to help. Do you have ideas, questions, or need any more information to get started?

**Comment by josh-chamberlain** [comment]
It appears records are not kept of this. Recommended a survey of incarcerated people, as has been helpful in the past.
