### ISSUE TITLE
Allegheny County Jail PA Probation holds

### ISSUE THREAD

**Issue by BBarr-PDAP** [Police-Data-Accessibility-Project/data-projects#50]
Someone has requested help on a data project: 

**Submission notes**
------------------------------------------------------------------------------------------------------------------------------------------------------

How many people are on probation holds in Allegheny County Jail? 

**Location**
---------------------------------------------------------------------------------------------------------------------------------------------------

Allegheny County Jail

**Requirements**
---------------------------------------------------------------------------------------------------------------------------------------------------

Jail records

**How to help**
------------------------------------------------------------------------------------------------------------------------------------------------------

Leave a comment if you'd like to help. Do you have ideas, questions, or need any more information to get started?

**Comment by josh-chamberlain** [comment]
[Holding status breakdown](https://tableau.alleghenycounty.us/t/PublicSite/views/AC_JailPopulationManagement_Final/HoldingStatusBreakdown?iframeSizedToWindow=true&%3Aembed=y&%3Adisplay_spinner=no&%3AshowAppBanner=false&%3Aembed_code_version=3&%3AloadOrderID=0&%3Adisplay_count=no&%3AshowVizHome=no&%3Aorigin=viz_share_link), [Holding status trend](https://tableau.alleghenycounty.us/t/PublicSite/views/AC_JailPopulationManagement_Final/HoldingStatusTrend?iframeSizedToWindow=true&%3Aembed=y&%3Adisplay_spinner=no&%3AshowAppBanner=false&%3Aembed_code_version=3&%3AloadOrderID=0&%3Adisplay_count=no&%3AshowVizHome=no&%3Aorigin=viz_share_link)

42% as of 5/15/23
