### ISSUE TITLE
Allegheny County Jail solitary confinement 

### ISSUE THREAD

**Issue by BBarr-PDAP** [Police-Data-Accessibility-Project/data-projects#51]
Someone has requested help on a data project: 

**Submission notes**
------------------------------------------------------------------------------------------------------------------------------------------------------

How many inmates are being placed in solitary confinement, how often does it happen, and on average how long are people kept in solitary confinement? 

**Location**
---------------------------------------------------------------------------------------------------------------------------------------------------

Allegheny County jail 

**Requirements**
---------------------------------------------------------------------------------------------------------------------------------------------------

Jail records

**How to help**
------------------------------------------------------------------------------------------------------------------------------------------------------

Leave a comment if you'd like to help. Do you have ideas, questions, or need any more information to get started?

**Comment by josh-chamberlain** [comment]
[Segregated Housing reports](https://data-sources.pdap.io/data-sources/recabQ04zvUH4RKQ0) tell the story, but require analysis
