### ISSUE TITLE
Allegheny County Jail PA Youth population

### ISSUE THREAD

**Issue by BBarr-PDAP** [Police-Data-Accessibility-Project/data-projects#52]
Someone has requested help on a data project: 

**Submission notes**
------------------------------------------------------------------------------------------------------------------------------------------------------

What portion of the population in Allegheny County Jail are youth (under 18)? What is the average stay for youth in ACJ? 

**Location**
---------------------------------------------------------------------------------------------------------------------------------------------------

Allegheny County Jail

**Requirements**
---------------------------------------------------------------------------------------------------------------------------------------------------

Jail records 

**How to help**
------------------------------------------------------------------------------------------------------------------------------------------------------

Leave a comment if you'd like to help. Do you have ideas, questions, or need any more information to get started?

**Comment by josh-chamberlain** [comment]
[Population overview](https://tableau.alleghenycounty.us/t/PublicSite/views/AC_JailPopulationManagement_Final/JailPopulationOverview?iframeSizedToWindow=true&%3Aembed=y&%3Adisplay_spinner=no&%3AshowAppBanner=false&%3Aembed_code_version=3&%3AloadOrderID=0&%3Adisplay_count=no&%3AshowVizHome=no&%3Aorigin=viz_share_link). It's not possible to learn who these youth are without court docket analysis.

Related to https://github.com/Police-Data-Accessibility-Project/scrapers/issues/239
