### ISSUE TITLE
Allegheny County Jail PA average medical costs

### ISSUE THREAD

**Issue by BBarr-PDAP** [Police-Data-Accessibility-Project/data-projects#55]
Someone has requested help on a data project: 

**Submission notes**
------------------------------------------------------------------------------------------------------------------------------------------------------

What are the average medical costs for inmates at the Allegheny County Jail

**Location**
---------------------------------------------------------------------------------------------------------------------------------------------------

Allegheny County Jail

**Requirements**
---------------------------------------------------------------------------------------------------------------------------------------------------

Medical records

**How to help**
------------------------------------------------------------------------------------------------------------------------------------------------------

Leave a comment if you'd like to help. Do you have ideas, questions, or need any more information to get started?

**Comment by josh-chamberlain** [comment]
This requires documentation which will almost always be denied citing HIPAA.
