### ISSUE TITLE
Oshawa Ont death related incident

### ISSUE THREAD

**Issue by BBarr-PDAP** [Police-Data-Accessibility-Project/data-projects#61]
Someone has requested help on a data project: 

**Submission notes**
------------------------------------------------------------------------------------------------------------------------------------------------------

Previous death linked to the same house on Durham 28 Road Oshawa, Ontario.  

**Location**
---------------------------------------------------------------------------------------------------------------------------------------------------

Oshawa Ont 

**How to help**
------------------------------------------------------------------------------------------------------------------------------------------------------

Leave a comment if you'd like to help. Do you have ideas, questions, or need any more information to get started?

**Comment by josh-chamberlain** [comment]
Our response:

You requested some information from Oshawa—this is in Ontario, Canada, correct? Our database only covers the United States, but it looks like you can request death investigation results from this website: https://www.ontario.ca/page/death-investigations

You can get the forms either:
- by contacting your regional office
- emailing OCC.Inquiries@ontario.ca.
 
Hopefully that’s helpful. Good luck in your search!
