### ISSUE TITLE
Pittsburgh Pa Protest arrests

### ISSUE THREAD

**Issue by BBarr-PDAP** [Police-Data-Accessibility-Project/data-projects#62]
Someone has requested help on a data project: 

**Submission notes**
------------------------------------------------------------------------------------------------------------------------------------------------------

I've been looking through UJS portal for cases related to arrests at the protest last night.

I was Legal Observing a protest last night when we saw police running a few blocks away, so we followed them. 
Police had handcuffed a naked woman who was having a mental health episode. An ambulance drove her away. And they arrested a man for standing on the street instead of the sidewalk. We tried to get the man's name, but the police wouldn't let us. 
We're searching the UJS portal through Date Filed. He's a black man in his 20s or 30s. Potential charges are: resisting arrest, terroristic threats, obstructing administration of the law, etc. He was arrested at around 5:40pm on 5/7/24. I bet he's been arraigned by now.

**Location**
---------------------------------------------------------------------------------------------------------------------------------------------------

Pittsburgh, PA

**Requirements**
---------------------------------------------------------------------------------------------------------------------------------------------------

Arrest records, court records

**How to help**
------------------------------------------------------------------------------------------------------------------------------------------------------

Leave a comment if you'd like to help. Do you have ideas, questions, or need any more information to get started?

**Comment by josh-chamberlain** [comment]
A volunteer found a potential docket: https://ujsportal.pacourts.us/Report/MdjDocketSheet?docketNumber=MJ-05003-CR-0002421-2024&dnh=k39BezDFiZUz7v3DfAElJA%3D%3D
