### ISSUE TITLE
Allegheny Count Jail death related incidents

### ISSUE THREAD

**Issue by BBarr-PDAP** [Police-Data-Accessibility-Project/data-projects#63]
Someone has requested help on a data project: 

**Submission notes**
------------------------------------------------------------------------------------------------------------------------------------------------------

We want to know if the jail has an internal document or database for tracking deaths of incarcerated people and the statuses of their investigations. We need to RTK it.

**Location**
---------------------------------------------------------------------------------------------------------------------------------------------------

Allegheny County Jail - PA

**Requirements**
---------------------------------------------------------------------------------------------------------------------------------------------------

internal jail investigations

**How to help**
------------------------------------------------------------------------------------------------------------------------------------------------------

Leave a comment if you'd like to help. Do you have ideas, questions, or need any more information to get started?

**Comment by josh-chamberlain** [comment]
RTK request made with the ACJ 5/8/24. #W018121-050824

their response was to share the mortality review here: https://www.alleghenycounty.us/files/assets/county/v/1/government/jail/reports/ncchc_mortality-review-technical-assistance-report_revised.pdf

Another request made 6/13/24 for 2010–23.
