### ISSUE TITLE
Martinsburg WV Court records

### ISSUE THREAD

**Issue by BBarr-PDAP** [Police-Data-Accessibility-Project/data-projects#66]
Someone has requested help on a data project: 

**Submission notes**
------------------------------------------------------------------------------------------------------------------------------------------------------

702 Virginia Ave, Martinsburg, WV 25401 is an old address, but its between that and Berkeley springs that i know of. 

**Location**
---------------------------------------------------------------------------------------------------------------------------------------------------

Dexter's Laburgertory

**Requirements**
---------------------------------------------------------------------------------------------------------------------------------------------------

Any court records

**How to help**
------------------------------------------------------------------------------------------------------------------------------------------------------

Leave a comment if you'd like to help. Do you have ideas, questions, or need any more information to get started?

**Comment by josh-chamberlain** [comment]
Needed more details, but requestor was unresponsive.
