### ISSUE TITLE
Allegheny County Jail PA youth education information 

### ISSUE THREAD

**Issue by BBarr-PDAP** [Police-Data-Accessibility-Project/data-projects#67]
Someone has requested help on a data project: 

**Submission notes**
------------------------------------------------------------------------------------------------------------------------------------------------------

How is schooling delivered to youth inside? Who is responsible for developing the curriculum? Who delivers the curriculum?

**Location**
---------------------------------------------------------------------------------------------------------------------------------------------------

Allegheny County Jail - PA

**Requirements**
---------------------------------------------------------------------------------------------------------------------------------------------------

Policy on education 

**How to help**
------------------------------------------------------------------------------------------------------------------------------------------------------

Leave a comment if you'd like to help. Do you have ideas, questions, or need any more information to get started?

**Comment by josh-chamberlain** [comment]
Recommended an interview, survey, or FOIA request for policies.
