### ISSUE TITLE
Kansas City MO individual record

### ISSUE THREAD

**Issue by BBarr-PDAP** [Police-Data-Accessibility-Project/data-projects#69]
Someone has requested help on a data project: 

**Submission notes**
------------------------------------------------------------------------------------------------------------------------------------------------------

I want to know if my ex is out of prison so i may be able to take precautions.

**Location**
---------------------------------------------------------------------------------------------------------------------------------------------------

Kansas City, Missouri 

**Requirements**
---------------------------------------------------------------------------------------------------------------------------------------------------

Arrest records

**How to help**
------------------------------------------------------------------------------------------------------------------------------------------------------

Leave a comment if you'd like to help. Do you have ideas, questions, or need any more information to get started?

**Comment by josh-chamberlain** [comment]
Requestor was unresponsive to requests for more info.
