### ISSUE TITLE
PA Juvenile Probation Office  

### ISSUE THREAD

**Issue by BBarr-PDAP** [Police-Data-Accessibility-Project/data-projects#71]
Someone has requested help on a data project: 

**Submission notes**
------------------------------------------------------------------------------------------------------------------------------------------------------

I was wondering if you have the most recent PaDRAI data for the PA Juvenile Probation Office, specifically Allegheny county. 

The most recent I have is 2019. I am told by the state that it is the property of said office, and they can't disclose it on their own. Do you know if the most recent data (2022) is available anywhere? (I am asking probation to release it.)

**Location**
---------------------------------------------------------------------------------------------------------------------------------------------------

Allegheny County - PA

**How to help**
------------------------------------------------------------------------------------------------------------------------------------------------------

Leave a comment if you'd like to help. Do you have ideas, questions, or need any more information to get started?

**Comment by josh-chamberlain** [comment]
Requestor getting data another way and sharing it with us.
