### ISSUE TITLE
Pittsburgh PA Police officer roster

### ISSUE THREAD

**Issue by BBarr-PDAP** [Police-Data-Accessibility-Project/data-projects#72]
Someone has requested help on a data project: 

**Submission notes**
------------------------------------------------------------------------------------------------------------------------------------------------------

A user suggested that it would be nice to have an officer roster for Pittsburgh police, which could help flesh out the database. When court dockets reference an officer or badge number, those cases could be linked with the relevant department, precinct, etc.

**Location**
---------------------------------------------------------------------------------------------------------------------------------------------------

Pittsburgh Police - PA

**Requirements**
---------------------------------------------------------------------------------------------------------------------------------------------------

Officer roster

**How to help**
------------------------------------------------------------------------------------------------------------------------------------------------------

Leave a comment if you'd like to help. Do you have ideas, questions, or need any more information to get started?

**Comment by josh-chamberlain** [comment]
Withdrawal reason: High friction required, and they didn't know whether the data would be useful.
