### ISSUE TITLE
Arkansas Police data collection

### ISSUE THREAD

**Issue by BBarr-PDAP** [Police-Data-Accessibility-Project/data-projects#73]
Someone has requested help on a data project: 

**Submission notes**
------------------------------------------------------------------------------------------------------------------------------------------------------

- arrest records with demographic info
- procedural practices
- laws & policies
- connections between organizations
- general ""system"" mapping

**Location**
---------------------------------------------------------------------------------------------------------------------------------------------------

Ashley, Bradley, Chicot, Desha, and Drew counties in Arkansas

**Requirements**
---------------------------------------------------------------------------------------------------------------------------------------------------

Data collection

**How to help**
------------------------------------------------------------------------------------------------------------------------------------------------------

Leave a comment if you'd like to help. Do you have ideas, questions, or need any more information to get started?

**Comment by josh-chamberlain** [comment]
Withdrawal reason: After further reviewing the data available from the dockets and the requirements on our end to review and analyze such data, I think the scraper is unnecessary. That said, I truly I appreciate your willingness to assist and find a volunteer able to write the code. The airtable that you provided was truly enlightening on the resources (or lack thereof) that these communities have and how that impacts data collection and reporting.
