### ISSUE TITLE
Fort Worth Police Department legal fees for police lawsuits

### ISSUE THREAD

**Issue by BBarr-PDAP** [Police-Data-Accessibility-Project/data-projects#74]
Someone has requested help on a data project: 

**Submission notes**
------------------------------------------------------------------------------------------------------------------------------------------------------

The requestor asked if it would be possible to measure or find the origin of legal fees for activity in ongoing or past police lawsuits.

**Location**
---------------------------------------------------------------------------------------------------------------------------------------------------

Fort Worth Police Department - TX 

**Requirements**
---------------------------------------------------------------------------------------------------------------------------------------------------

Legal payments 

**How to help**
------------------------------------------------------------------------------------------------------------------------------------------------------

Leave a comment if you'd like to help. Do you have ideas, questions, or need any more information to get started?

**Comment by josh-chamberlain** [comment]
Fees were not visible on public 990s for non-profit police legal organizations. Closing as `Complete` because we did answer the question—a records request may reveal more.
