### ISSUE TITLE
Pittsburgh PA License plate reader data

### ISSUE THREAD

**Issue by BBarr-PDAP** [Police-Data-Accessibility-Project/data-projects#75]
Someone has requested help on a data project: 

**Submission notes**
------------------------------------------------------------------------------------------------------------------------------------------------------

Can you get any access to Pittsburgh police license plate reader data or how the Bureau deploys its squad cars?

**Location**
---------------------------------------------------------------------------------------------------------------------------------------------------

Pittsburgh Bureau of Police - PA 

**Requirements**
---------------------------------------------------------------------------------------------------------------------------------------------------

License plate reader data

**How to help**
------------------------------------------------------------------------------------------------------------------------------------------------------

Leave a comment if you'd like to help. Do you have ideas, questions, or need any more information to get started?

**Comment by josh-chamberlain** [comment]
The requestor stated they had another source for the information.
