### ISSUE TITLE
Pittsburgh Police Predictive policing policy

### ISSUE THREAD

**Issue by BBarr-PDAP** [Police-Data-Accessibility-Project/data-projects#76]
Someone has requested help on a data project: 

**Submission notes**
------------------------------------------------------------------------------------------------------------------------------------------------------

The Bureau had this predictive policing project up to 2019.
https://www.cmu.edu/metro21/projects/smart-infrastructure/reducing-crime.html
 
Who can I talk to to find out if the Bureau is using predictive policing now?

**Location**
---------------------------------------------------------------------------------------------------------------------------------------------------

Pittsburgh Bureau of Police - PA

**Requirements**
---------------------------------------------------------------------------------------------------------------------------------------------------

Policies

**How to help**
------------------------------------------------------------------------------------------------------------------------------------------------------

Leave a comment if you'd like to help. Do you have ideas, questions, or need any more information to get started?

**Comment by josh-chamberlain** [comment]
Requestor withdrew.

connected with Atlas of Surveillance: https://atlasofsurveillance.org/search?utf8=%E2%9C%93&location=pittsburgh&commit=Search+the+Data
