### ISSUE TITLE
Child abuse police reports

### ISSUE THREAD

**Issue by BBarr-PDAP** [Police-Data-Accessibility-Project/data-projects#77]
Someone has requested help on a data project: 

**Submission notes**
------------------------------------------------------------------------------------------------------------------------------------------------------

I'm trying to look at police reports for cases of child abuse to look at the rhetoric used.

**Location**
---------------------------------------------------------------------------------------------------------------------------------------------------

Child and Family Services

**Requirements**
---------------------------------------------------------------------------------------------------------------------------------------------------

Court cases and policies

**How to help**
------------------------------------------------------------------------------------------------------------------------------------------------------

Leave a comment if you'd like to help. Do you have ideas, questions, or need any more information to get started?

**Comment by josh-chamberlain** [comment]
They needed the information in 5 days, and we missed the deadline.
