### ISSUE TITLE
Police Misconduct & Complaints multiple agencies 

### ISSUE THREAD

**Issue by BBarr-PDAP** [Police-Data-Accessibility-Project/data-projects#78]
Someone has requested help on a data project: 

**Submission notes**
------------------------------------------------------------------------------------------------------------------------------------------------------

"I am looking for number of sworn officers, total number of complaints, total numbers of sustained complaints, total number of use of force complaints, total number of sustained use of force complaints, total citizen complaints, and total internal complaints, all separated by year from the years 2000-2023. Specifically, I am looking for this information from the following agencies:
Albequerque Police Dept
Atlanta Police Dept
Austin Police Dept
Avondale Police Dept
Baltimore Police Dept
Boise Police Dept
Boston Police Dept
Broward Cty. Sheriff's Office
California Hwy Patrol
Charlotte-Mecklenburg Police Dept
Chicago Police Dept
Cincinnati Police Dept
Cleveland Police Dept
Cobb Cty. Police Dept
Columbus Police Dept
Concord Police Dept
Concord Police Dept
Contra Costa Cty. Sheriff's Office
Cook Cty. Sherriff's Office
Dallas Police Dept
Decatur Police Dept
DeKalb Cty. Police Dept
Denver Police Dept
Detroit State Police
Eden Prairie Police Dept
Edgewood Police Dept
El Paso Police Dept
Evansville Police Dept
Florida Hwy Patrol
Fort Wayne Police Dept
Fort Worth Police Dept
Fruitland Police Dept
Harris Cty. Sheriff's Office
Hemet Police Dept
Honolulu Police Dept
Houston Police Dept
Howard Cty. Police Dept
Illinois State Police
Indiannapolis Metro. Police Dept
Jackson Township Police Dept
Jacksonville Sheriff's Office
Kansas City Police Dept
Las Vegas Metro. Police Dept
Lincolnton Police Dept
Los Angeles Cty. Police Dept
Los Angeles Police Dept
Louisville Metro. Police Dept
Manatee Cty. Sheriff's Office
Massachusetts State Police
Memphis Police Dept
Metro. Police Dept
Miami-Dade Cty. Police Dept
Michigan State Police
Milwaukee Police Dept
Minnesota State Patrol
Montgomery Cty. Police Dept
Naperville Police Dept
Nashville-Davidson Cty. Police Dept
New Bedford Police Dept
New Hampshire State Police
New Orleans Police Dept
New York City Police Dept
Newark Police Dept
North Carolina State Hwy. Patrol
Ohio Hwy Patrol
Oklahoma City Police Dept
Oldham Cty. Sheriff's Office
Orange Cty. Sheriff's Dept
Overland Park Police Dept
Pennsylvania State Police Dept
Phelps Cty. Sheriff's Office
Philadelphia Police Dept
Phoenix Police Dept
Pocatello Police Dept
Polk City Sheriff's Office
Port Authority
Prince George's Cty. Police Dept
Pueblo City Sheriff's Office
Quincy Police Dept
Raleigh Police Dept
Riverside Cty. Sheriff's Dept
San Antonio Police Dept
San Bernadino Cty. Sheriff's Dept
San Diego Police Dept
San Francisco Police Dept
San Jose Police Dept
Schaumburg Police Dept
Seattle Police Dept
Springfield Police Dept
St. Mary's Cty. Sheriff's Office
Summit Cty. Sheriff's Office
Tampa Police Dept
Texas Dept. Public Safety
Town and Country Police Dept
Tucson Police Dept
Tulsa Cty. Sheriff's Office
Virginia State Police
Waco Police Dept
Waterloo Police Dept
Yellowstone Cty. Sheriff's Office"

**Location**
---------------------------------------------------------------------------------------------------------------------------------------------------

Multiple agencies

**Requirements**
---------------------------------------------------------------------------------------------------------------------------------------------------

Complaints & Misconduct; use of force reports; personnel records; annual & monthly reports

**How to help**
------------------------------------------------------------------------------------------------------------------------------------------------------

Leave a comment if you'd like to help. Do you have ideas, questions, or need any more information to get started?

**Comment by josh-chamberlain** [comment]
This request was withdrawn, and they are re-evaluating the scope
